version: '3'
services:
  frontend.api:
    image: frontend:latest
    ports:
    - "80:80"
    container_name: frontend.api
    links:
    - redis.service
  redis.service:
    image: redis
    container_name: redis.service
